# exp: TextClassification
# mode:
#     - train

# models:
#     hf_text_classification_model:
#         - bert-base-uncased

# textLabel: text
# labelLabel: label
# id2label:
#     0: Negative
#     1: Positive

# trainfpath: nlp_midterm/traindata.tsv
# validfpath: nlp_midterm/evaldata.tsv
# modelfpath: nlp_midterm/trained_bert_3
      

exp: TextClassification  

mode:
  - evaluate 

models:
    hf_text_classification_model:
        - nlp_midterm/trained_bert_1

datafpath: nlp_midterm/evaldatatest.tsv
predfpath: nlp_midterm/bert_trained_eval1.tsv




