# exp: TextClassification

# mode: 
#     - train

# models: 
#       hf_text_classification_model:
#           - gpt2

# labelLabel: label
# textLabel: text
# id2label:
#     0 : Negative
#     1 : Positive
          
# trainfpath: midterm/traindata.tsv
# validfpath: midterm/validdata.tsv
#specify models 1-3
# modelfpath: midterm/gpt2model3

exp: TextClassification

mode:
    - evaluate

models: 
      hf_text_classification_model:
          - midterm/gpt2model3
          #specify models 1-3

datafpath: midterm/evaldatatest.tsv

predfpath: midterm/gpt2model3Eval.tsv
#specify models 1-3

id2label:
    0 : Negative
    1 : Positive
